Test: add a test which drop a database while river runs
In case of exception while reading CouchDB `_changes` we can have a failing test although the connection should be restarted and get the content.

Test which get that error is `testCreateCouchdbDatabaseWhileRunning_17()`:

```
2014-08-08 11:35:54,027][WARN ][org.elasticsearch.river.couchdb] [node_0] [couchdb][elasticsearch_couch_test_test_create_couchdb_database_while_running_17] failed to read from _changes, throttling....
java.io.FileNotFoundException: http://localhost:5984/elasticsearch_couch_test_test_create_couchdb_database_while_running_17/_changes?feed=continuous&include_docs=true&heartbeat=10000
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1624)
	at org.elasticsearch.river.couchdb.CouchdbRiver$Slurper.run(CouchdbRiver.java:538)
	at java.lang.Thread.run(Thread.java:745)
```

This test covers this case.

Closes #71.

(cherry picked from commit a80a729)